name: trivia_quiz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
  - family: Sen
    fonts:
      - asset: assets/fonts/Sen-Regular.ttf
        weight: 400
      - asset: assets/fonts/Sen-Bold.ttf
        weight: 700
      - asset: assets/fonts/Sen-ExtraBold.ttf
        weight: 800

